# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-24 10:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extracted_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickness_name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Original_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='forms/')),
                ('sickness_form', models.CharField(max_length=82)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=30)),
                ('position', models.CharField(choices=[('Doctor', 'DOCTOR'), ('Nurse', 'Nurse')], default='Nurse', max_length=50)),
                ('phone_number', models.IntegerField()),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('pic', models.ImageField(blank=True, default='no profile pic', upload_to='avatar/')),
                ('work_id', models.CharField(blank=True, max_length=30)),
                ('hospital_name', models.CharField(blank=True, max_length=54, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='original_image',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='health_app.Profile'),
        ),
        migrations.AddField(
            model_name='extracted_data',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracts', to='health_app.Original_image'),
        ),
        migrations.AddField(
            model_name='extracted_data',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.Profile'),
        ),
    ]
