# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracted_data',
            old_name='name',
            new_name='sickness_name',
        ),
        migrations.RenameField(
            model_name='original_image',
            old_name='sickness',
            new_name='sickness_form',
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='', upload_to='avatar/'),
        ),
    ]
